<?php

declare(strict_types=1);

namespace Tugrul\ApiGen\Tests\Generator;

use PHPUnit\Framework\TestCase;
use Tugrul\ApiGen\Generator\{DefaultNamingStrategy, StubGenerator, SubNamespaceNamingStrategy, SuffixNamingStrategy};
use Tugrul\ApiGen\Tests\Fixtures\{PetApi, SimpleApi};

final class StubGeneratorTest extends TestCase
{
    private string $outputDir;

    protected function setUp(): void
    {
        parent::setUp();
        $this->outputDir = sys_get_temp_dir() . '/apigen_gen_' . bin2hex(random_bytes(4));
        mkdir($this->outputDir, 0755, true);
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        $this->rmdirRecursive($this->outputDir);
    }

    private function gen(string $naming = 'default'): StubGenerator
    {
        $strategy = match ($naming) {
            'suffix' => new SuffixNamingStrategy('Stub'),
            'subns'  => new SubNamespaceNamingStrategy('Generated'),
            default  => new DefaultNamingStrategy(),
        };

        return new StubGenerator($this->outputDir, $strategy);
    }

    // ── Return value from generate() ──────────────────────────────────────────

    public function test_generate_returns_generated_stub_value_object(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);

        self::assertSame(SimpleApi::class, $stub->interfaceClass);
        self::assertStringEndsWith('SimpleApiStub', $stub->stubShortName);
        self::assertStringContainsString('SimpleApiStub', $stub->stubClass);
        self::assertFileExists($stub->filePath);
    }

    public function test_generate_throws_for_non_interface(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessageMatches('/must be an interface/');

        $this->gen()->generate(\stdClass::class);
    }

    public function test_generate_all_returns_array_of_stubs(): void
    {
        $stubs = $this->gen('suffix')->generateAll([SimpleApi::class, PetApi::class]);

        self::assertCount(2, $stubs);
        self::assertSame(SimpleApi::class, $stubs[0]->interfaceClass);
        self::assertSame(PetApi::class,   $stubs[1]->interfaceClass);
    }

    // ── Generated file contents ───────────────────────────────────────────────

    public function test_generated_file_has_auto_generated_marker(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('AUTO-GENERATED by Tugrul\ApiGen', $code);
        self::assertStringContainsString(SimpleApi::class, $code);
    }

    public function test_generated_class_implements_interface(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('implements', $code);
        self::assertStringContainsString('SimpleApi', $code);
    }

    public function test_generated_class_has_sdk_client_constructor(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('SdkClient', $code);
        self::assertStringContainsString('__construct', $code);
    }

    // ── HTTP method generation ────────────────────────────────────────────────

    public function test_get_method_generated_correctly(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->method('GET')", $code);
        self::assertStringContainsString("->path('/users')", $code);
        self::assertStringContainsString('listUsers', $code);
    }

    public function test_delete_method_generated_without_return(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('deleteUser', $code);

        $methodBody = $this->extractMethodBody($code, 'deleteUser');

        self::assertStringNotContainsString('return $this->client->execute', $methodBody);
        self::assertStringContainsString('$this->client->execute', $methodBody);
    }

    public function test_non_void_method_uses_return(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        $methodBody = $this->extractMethodBody($code, 'listUsers');

        self::assertStringContainsString('return $this->client->execute', $methodBody);
    }

    /**
     * Extract a method body from generated code by finding the opening brace
     * of the method and then tracking brace depth to find the matching closing brace.
     * This correctly handles path params like /users/{id} which contain '}' inside strings.
     */
    private function extractMethodBody(string $code, string $methodName): string
    {
        $start = strpos($code, 'function ' . $methodName);
        if ($start === false) {
            return '';
        }

        // Find the opening brace of the method body
        $open = strpos($code, '{', $start);
        if ($open === false) {
            return '';
        }

        // Walk forward tracking brace depth to find the true closing brace
        $depth = 0;
        $len   = strlen($code);

        for ($i = $open; $i < $len; $i++) {
            if ($code[$i] === '{') {
                $depth++;
            } elseif ($code[$i] === '}') {
                $depth--;
                if ($depth === 0) {
                    return substr($code, $open, $i - $open + 1);
                }
            }
        }

        return substr($code, $open);
    }

    // ── Parameter binding ─────────────────────────────────────────────────────

    public function test_path_param_generated(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->pathParam('petId'", $code);
    }

    public function test_query_param_with_custom_name_generated(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        // #[Query('per_page')] maps to ->queryParam('per_page', $perPage)
        self::assertStringContainsString("->queryParam('per_page'", $code);
    }

    public function test_query_map_generated(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('->queryMap($filters)', $code);
    }

    public function test_body_param_generated(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->body(\$data, 'json')", $code);
    }

    public function test_form_fields_bundled_as_body(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        // registerPet has #[Field] params — should bundle them
        self::assertStringContainsString("->body([", $code);
        self::assertStringContainsString("'form'", $code);
    }

    public function test_multipart_parts_bundled_as_body(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("'multipart'", $code);
    }

    public function test_dynamic_header_param_generated(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->header('X-Locale'", $code);
    }

    // ── Modifiers ─────────────────────────────────────────────────────────────

    public function test_no_auth_generates_disable_auth_call(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('->disableAuth()', $code);
    }

    public function test_use_auth_generates_use_auth_class_call(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->useAuthClass(", $code);
    }

    public function test_static_header_from_class_included_in_every_method(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        // Accept header set at class level via #[StaticHeader]
        self::assertStringContainsString("->header('Accept', 'application/json')", $code);
    }

    public function test_base_url_override_generated(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->baseUrl('https://records.example.com')", $code);
    }

    public function test_returns_attribute_generates_return_type_call(): void
    {
        $stub = $this->gen('suffix')->generate(PetApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString("->returnType('array')", $code);
    }

    // ── Naming strategies affect output ───────────────────────────────────────

    public function test_suffix_strategy_names_class_correctly(): void
    {
        $stub = $this->gen('suffix')->generate(SimpleApi::class);

        self::assertSame('SimpleApiStub', $stub->stubShortName);
        self::assertStringEndsWith('SimpleApiStub.php', $stub->filePath);
    }

    public function test_sub_namespace_strategy_creates_sub_directory(): void
    {
        $stub = $this->gen('subns')->generate(SimpleApi::class);
        $code = file_get_contents($stub->filePath);

        self::assertStringContainsString('Generated', $stub->stubNamespace);
        self::assertStringContainsString('Generated', $stub->filePath);
    }

    // ── Conflict detection ────────────────────────────────────────────────────
    //
    // We use FALLBACK_FULL_NAMESPACE so the output path is fully deterministic
    // in the test environment regardless of whether a composer.json is found.

    private function genForConflict(): StubGenerator
    {
        $resolver = new \Tugrul\ApiGen\Generator\OutputPathResolver(
            $this->outputDir,
            \Tugrul\ApiGen\Generator\OutputPathResolver::FALLBACK_FULL_NAMESPACE,
        );

        return new StubGenerator($this->outputDir, new DefaultNamingStrategy(), $resolver);
    }

    public function test_impl_suffix_used_when_file_exists_and_is_not_generated(): void
    {
        // Ask the resolver itself where it will write the file — then pre-create it
        $rc           = new \ReflectionClass(SimpleApi::class);
        $resolver     = new \Tugrul\ApiGen\Generator\OutputPathResolver(
            $this->outputDir,
            \Tugrul\ApiGen\Generator\OutputPathResolver::FALLBACK_FULL_NAMESPACE,
        );
        $expectedPath = $resolver->resolve($rc, 'Tugrul\\ApiGen\\Tests\\Fixtures', 'SimpleApi');

        @mkdir(dirname($expectedPath), 0755, true);
        file_put_contents($expectedPath, '<?php // hand-written, not generated');

        $stub = $this->genForConflict()->generate(SimpleApi::class);

        self::assertSame('SimpleApiImpl', $stub->stubShortName);
    }

    public function test_no_impl_suffix_when_existing_file_is_auto_generated(): void
    {
        $rc           = new \ReflectionClass(SimpleApi::class);
        $resolver     = new \Tugrul\ApiGen\Generator\OutputPathResolver(
            $this->outputDir,
            \Tugrul\ApiGen\Generator\OutputPathResolver::FALLBACK_FULL_NAMESPACE,
        );
        $expectedPath = $resolver->resolve($rc, 'Tugrul\\ApiGen\\Tests\\Fixtures', 'SimpleApi');

        @mkdir(dirname($expectedPath), 0755, true);
        file_put_contents($expectedPath, '<?php // AUTO-GENERATED by Tugrul\ApiGen\Generator\StubGenerator.');

        $stub = $this->genForConflict()->generate(SimpleApi::class);

        self::assertSame('SimpleApi', $stub->stubShortName); // no Impl — safe to overwrite
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function rmdirRecursive(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        foreach (glob($dir . '/*') ?: [] as $entry) {
            is_dir($entry) ? $this->rmdirRecursive($entry) : unlink($entry);
        }

        rmdir($dir);
    }
}
